- main/plugins/org.talend.mdm.workbench/pom.xml
https://jira.talendforge.org/browse/TUP-19810
when building using mvn, a warning is displayed in the console : 
<snip> [WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-clean-plugin is missing. </snip>
no more warning
- [*] No
> TUP-19810 : fix mvn build warning

- main/plugins/org.talend.mdm.workbench/src/com/amalto/workbench/dialogs/SimpleXpathInputDialog.java
https://jira.talendforge.org/browse/TMDM-12364.
Check or uncheck 'Render in the main tab' checkbox can not affect OK button status
Check or uncheck 'Render in the main tab' checkbox will set OK button enabled if xpath is valid.
> TMDM-12364 Check or uncheck 'Render in the main tab' checkbox will trigger OK button enabled if xpath is valid.

- main/plugins/org.talend.mdm.repository/src/main/java/org/talend/mdm/repository/core/datacontent/impl/ExportDataContentProcess.java
On Windows, if the file name include dot at the end of a filename, it will be removed by system, so it can overwrite file without dot at the end of filename.
This fixing will add a suffix to the end of the file name, so it won't overwrite even the file name includes a dot at the end.
> TMDM-12317 [Studio] Record files obtained from a server export can be overwritten in some cases

- main/plugins/org.talend.mdm.workbench/src/com/amalto/workbench/actions/XSDEditParticleAction.java
- main/plugins/org.talend.mdm.workbench/src/com/amalto/workbench/detailtabs/sections/handlers/ElementWrapperCommitHandler.java
- main/plugins/org.talend.mdm.workbench/src/com/amalto/workbench/providers/XSDTreeLabelProvider.java
Change FK to reference in datamodel editor while FK icon not disappeared in ER editor
link: https://jira.talendforge.org/browse/TMDM-12543
The FK icon disappear after change FK to reference
> TMDM-12543 Change FK to reference in datamodel editor while FK icon not disappeared in ER editor

- main/plugins/org.talend.mdm.workbench/src/com/amalto/workbench/actions/XSDEditParticleAction.java
https://jira.talendforge.org/browse/TMDM-12664
Fixed showing error dialog when modifying reference element to simple element.
No error dialog pops when modify reference element to simple element.
> TMDM-12664  Modify reference element to simple element will show error.

- main/plugins/org.talend.mdm.workbench/src/com/amalto/workbench/actions/XSDEditParticleAction.java
https://jira.talendforge.org/browse/TMDM-12664
Fixed showing error dialog when modifying reference element to simple element.
No error dialog pops when modify reference element to simple element.
> TMDM-12664 Modify reference element to simple element will show error.

- main/plugins/org.talend.mdm.workbench/src/com/amalto/workbench/utils/HttpClientUtil.java
Can not run recreate table when switch to other language
link: https://jira.talendforge.org/browse/TMDM-12686
About bug: when invoke "recreate table" ,the studio will append  parameter "?force=True" at end of request URL, it causes two "?" character at URL(another is "?lang"),when this request arrives server the second parameter "force" is ignored, because it needn't "lang" parameter when "recreate table" so remove it to fix this issue.
It can send recreate table PUT request successfully.
If this PR contains a breaking change, please …
> TMDM-12686  [Impact Analysis] Always display result in English while switching to other language

- main/plugins/org.talend.designer.components.tomprovider/components/tMDMConnection/tMDMConnection_java.xml
- main/plugins/org.talend.designer.components.tomprovider/components/tMDMDelete/tMDMDelete_java.xml
- main/plugins/org.talend.designer.components.tomprovider/components/tMDMOutput/tMDMOutput_java.xml
- main/plugins/org.talend.designer.components.tomprovider/components/tMDMReadConf/tMDMReadConf_java.xml
- main/plugins/org.talend.designer.components.tomprovider/components/tMDMRouteRecord/tMDMRouteRecord_java.xml
- main/plugins/org.talend.designer.components.tomprovider/components/tMDMSP/tMDMSP_java.xml
- main/plugins/org.talend.designer.components.tomprovider/components/tMDMViewSearch/tMDMViewSearch_java.xml
- main/plugins/org.talend.designer.components.tomprovider/components/tMDMWriteConf/tMDMWriteConf_java.xml
https://jira.talendforge.org/browse/TMDM-12878
What is the current behavior? (You should also link to an open issue here)
What is the new behavior?
Version of woodstox-core is upgrade to 5.1.0 when doing TMDM-12490 Update cxf from 3.2.4 to 3.2.6 .
woodstox-core-5.1.0 is incompatible with stax2-api-3.1.4, need upgrade to stax2-api-4.1
> TMDM-12878 tMDMRestInput can not retrieve xml pattern data

- main/plugins/org.talend.mdm.workbench/src/com/amalto/workbench/editors/XObjectEditor.java
https://jira.talendforge.org/browse/TMDM-13200
After upgrade to eclipse 4.10, it throw exception when creating role.
Can open Role editor with no error blocking it.
> TMDM-13200 Fix problem that throw exception when creating a new "Role" after upgraded to Eclipse 4.10 .

- main/plugins/org.talend.mdm.repository/plugin.xml
- main/plugins/org.talend.mdm.repository/resources/system/datamodel/UpdateReport_0.1.xsd
- main/plugins/org.talend.mdm.repository/src/main/java/org/talend/mdm/repository/core/migrate/DataModelMigrationTask.java
- main/plugins/org.talend.mdm.repository/src/main/java/org/talend/mdm/repository/core/migrate/UpdateOperatorMigrationTask.java
- main/plugins/org.talend.mdm.repository/src/main/java/org/talend/mdm/repository/ui/wizards/imports/AbstractDataModelUpdator.java
- main/plugins/org.talend.mdm.repository/src/main/java/org/talend/mdm/repository/ui/wizards/imports/DataModelOperatorUpdator.java
- main/plugins/org.talend.mdm.repository/src/main/java/org/talend/mdm/repository/ui/wizards/imports/DataModelSchemaUpdator.java
- main/plugins/org.talend.mdm.repository/src/main/java/org/talend/mdm/repository/ui/wizards/imports/UpdatorProvider.java
- main/plugins/org.talend.mdm.repository/src/main/java/org/talend/mdm/repository/ui/wizards/imports/handlers/DataModelImportHandler.java
- main/plugins/org.talend.mdm.repository/src/main/java/org/talend/mdm/repository/ui/wizards/imports/handlers/ViewProcessImportHandler.java
- test/plugins/org.talend.mdm.repository.test/src/main/java/org/talend/mdm/repository/ui/wizards/imports/DataModelOperatorUpdatorTest.java
https://jira.talendforge.org/browse/TMDM-11900
With very high workload for Cluster mode, mdm Update Report may face error like Cannot insert duplicate key in object 'dbo.X_UPDATE_REPORT'. 
For Cluster mode problem, it needs change the update report schema, this led to Update Report change in standalone mode on studio side also. For Standalone mode, UpdateReport tables PK=Time + Source, add a new field UUID in UpdateReport .
If this PR contains a breaking change, please describe the impact and migration path for existing applications: …
> TMDM-11900 Update schema of UpdateReport, add 'UUID' field for standalone mode, additionally add acceptance for update data model condition operator.

- main/plugins/org.talend.mdm.repository/src/main/java/org/talend/mdm/repository/core/datacontent/impl/ImportDataContentProcess.java
https://jira.talendforge.org/browse/TMDM-13127
1. Import data to server from Studio always alert message of successfully(before eclipse platform upgrade to 4.10).
2. Import content to server & export content from server does not work after eclipse platform upgraded to 4.10 .
1. Import content to server & export content from server work after eclipse platform upgraded to 4.10 .
2. Import data to server from Studio failed will show give error message to user and log it.
If this PR contains a breaking change, please describe the impact …
> TMDM-13127 Error message will be shown when importing content to server failed.

- main/plugins/org.talend.mdm.workbench/src/com/amalto/workbench/utils/HttpClientUtil.java
Jira: https://jira.talendforge.org/browse/TMDM-13276
1.  Can not define the Content-type when invoking the REST API of the deploy data model
2. Set the Content-type to "application/xml" when invoking the REST API of the deploy data model
> TMDM-13276 [Impact Analysis] ElementType change (length) not reflected in PostgreSQL database tables

- main/plugins/org.talend.mdm.workbench/src/com/amalto/workbench/service/MissingJarService.java
When deploying workflow to MDM server in command line mode, it shows "MissingDialog". it causes an exception.
link: https://jira.talendforge.org/browse/TMDM-11937
Fixed "MissingJarService" shows UI dialog in command line mode
> TMDM-11937 [Studio] Bonita commandline upgrade 

- main/plugins/org.talend.mdm.workbench/META-INF/MANIFEST.MF
- main/plugins/org.talend.mdm.workbench/src/com/amalto/workbench/editors/xsdeditor/XSDEditor.java
If the datamodel is changed, when switching between ER and datamodel editor, it always pops a save dialog.
link: https://jira.talendforge.org/browse/TMDM-13199
No more save dialog pops in this case.
> TMDM-13199  [Eclipse 4.10] Throwing NPE when switch to ER editor after upgrading to Eclipse 4.10

- main/plugins/org.talend.mdm.repository.validate/src/org/talend/mdm/repository/ui/views/MDMProblemView.java
- main/plugins/org.talend.mdm.repository/src/main/java/org/talend/mdm/repository/ui/actions/OpenObjectAction.java
- main/plugins/org.talend.mdm.repository/src/main/java/org/talend/mdm/repository/ui/actions/RefreshAction.java
1. Throwing NPE when selecting a deleted workflow after refreshing.
2. Thread lock in random after calling "Edit properties" of workflow.
link: https://jira.talendforge.org/browse/TMDM-12929
3. Fix MDMProblemView throws NPE in remote mode when synchronizing new workflow created by another user.
Fixed above errors.
> TMDM-12929 [Studio] Make workflow sync work in remote mode.

- main/plugins/org.talend.mdm.repository/src/main/java/org/talend/mdm/repository/utils/RepositoryResourceUtil.java
Throwing error when creating a new workflow if have deleted a workflow without clean recycle bin.
link: https://jira.talendforge.org/browse/TMDM-13832
Fixed this error.
> TMDM-13832  Error in log when create a new workflow if have deleted a workflow without clean recycle bin.

- main/plugins/org.talend.mdm.repository/src/main/java/org/talend/mdm/repository/utils/RepositoryResourceUtil.java
Throwing error when creating a new workflow if have deleted a workflow without clean recycle bin.
link: https://jira.talendforge.org/browse/TMDM-13832
Fixed this error.
> TMDM-13832 Error in log when create a new workflow if have deleted a workflow without clean recycle bin. 

- main/plugins/org.talend.designer.components.tomprovider/components/tMDMDelete/tMDMDelete_java.xml
- main/plugins/org.talend.designer.components.tomprovider/components/tMDMViewSearch/tMDMViewSearch_java.xml
JIRA: https://jira.talendforge.org/browse/TMDM-13886
tMDMViewSearch and tMDMDelete run failed on JDK 11 without tMDMconnection
add the **activation.jar** for the two components.
> TMDM-13886 tMDMViewSearch and tMDMDelete run failed on JDK 11 without tMDMconnection

- main/plugins/org.talend.mdm.workbench/src/com/amalto/workbench/editors/xsdeditor/XSDEditor.java
https://jira.talendforge.org/browse/TMDM-13684
Properties view does not display while open a datamodel
Display Properties view while open a datamodel.
> TMDM-13684 Show 'properties' view when a data model opened.

- main/plugins/org.talend.designer.components.tomprovider/src/org/talend/designer/components/tomprovider/TomLocalComponentsProvider.java
- main/plugins/org.talend.mdm.workbench/src/com/amalto/workbench/actions/XSDDeleteParticleAction.java
- main/plugins/org.talend.mdm.workbench/src/com/amalto/workbench/actions/XSDEditParticleAction.java
- main/plugins/org.talend.mdm.workbench/src/com/amalto/workbench/utils/XSDUtil.java
- test/plugins/org.talend.mdm.workbench.test/src/main/java/com/amalto/workbench/utils/XSDUtilTest.java
https://jira.talendforge.org/browse/TMDM-13982
when field was renamed, sync the category annotation of entity.
> TMDM-13982 Synchronize "Category" annotation after rename a “field” of entity

- main/plugins/org.talend.mdm.workbench/src/com/amalto/workbench/providers/IXSDTreeLabelPoviderExAdapter.java
- main/plugins/org.talend.mdm.workbench/src/com/amalto/workbench/providers/XSDTreeLabelProvider.java
Can not display category annotation correctly
link: https://jira.talendforge.org/browse/TMDM-13897
Display category annotation in datamodel page
> TMDM-13897  [Studio] Implement displaying and deleting "Category" annotation in data model page.

- main/plugins/org.talend.mdm.workbench/src/com/amalto/workbench/utils/XSDUtil.java
- test/plugins/org.talend.mdm.workbench.test/src/main/java/com/amalto/workbench/utils/CategoryTest.java
- test/plugins/org.talend.mdm.workbench.test/src/main/java/com/amalto/workbench/utils/TestCategory05.xsd
XSDUtil return fields by alphabetical order and include "reference" field.
1. Show fields by default order the same with defined in entity instead of alphabetical order.
2. Fixed when calling XSDUtil.getFields(), the returned fields include 'reference' field.
3. Add and update JUnit for the above fix.
link:  https://jira.talendforge.org/browse/TMDM-14104
> TMDM-14104  [Studio] Filter by category improvement

- main/plugins/org.talend.mdm.workbench/src/com/amalto/workbench/utils/XSDAnnotationsStructure.java
Can't parse label_XX with uppercase
link https://jira.talendforge.org/browse/TMDM-14173
Fixed the category API can't parse label_XX with uppercase
> TMDM-14173  Tab Management - Parsing annotation of Category

- main/plugins/org.talend.designer.components.tomprovider/components/tMDMOutput/tMDMOutput_java.xml
The MDM component template file has dependency of log4j
link: https://jira.talendforge.org/browse/TMDM-14121
Remove the "IMPORT" of log4j from template file
> TMDM-14121  Support for Apache Log4j2

- main/plugins/org.talend.mdm.workbench/src/com/amalto/workbench/widgets/xmleditor/ExtensibleEditorContent.java
- main/plugins/org.talend.mdm.workbench/src/com/amalto/workbench/widgets/xmleditor/ExtensibleTextContentEditorPage.java
- test/plugins/org.talend.mdm.workbench.test/src/main/java/com/amalto/workbench/widgets/xmleditor/ExtensibleEditorContentTest.java
https://jira.talendforge.org/browse/TMDM-14523
Password still show in source editor for workflow & workflowcontext service jndi name, or for workflowtrigger & workflowcontexttrigger plugin for process.
Hide password in source editor. But allow user edit all parameters in source editor, if changed password contains * , all other changed parameters exception password will be saved.
> TMDM-14523 Password is in clear

- test/plugins/org.talend.mdm.repository.test/src/main/java/org/talend/mdm/repository/core/service/ContainerCacheServiceTest.java
- test/plugins/org.talend.mdm.repository.test/src/main/java/org/talend/mdm/repository/utils/RepositoryResourceUtilTest.java
https://jira.talendforge.org/browse/TMDM-13735
set mock object into global registered service may affect other test if does not recover.
Recover the global registered service after set mock object into.
workitem
> TMDM-13735 Studio JUnit enhancement to remove Powermock

- main/plugins/org.talend.mdm.workbench.serverexplorer/src/main/java/org/talend/mdm/workbench/serverexplorer/console/MDMServerMessageConsole.java
- main/plugins/org.talend.mdm.workbench/src/com/amalto/workbench/utils/HttpClientUtil.java
https://jira.talendforge.org/browse/TUP-27716
View server log/view server match log does not work if username/password contains special words.
View server log/view server match log work when username/password contains special words.
> TUP-27716 Make sure authorization works when username/password contains special words.

- main/plugins/org.talend.mdm.repository/src/main/java/org/talend/mdm/repository/core/service/wsimpl/transformplugin/CodeProjectPluginDetail.java
- main/plugins/org.talend.mdm.repository/src/main/java/org/talend/mdm/repository/core/service/wsimpl/transformplugin/DumpAndGoPluginDetail.java
- main/plugins/org.talend.mdm.repository/src/main/java/org/talend/mdm/repository/core/service/wsimpl/transformplugin/GroovyPluginDetail.java
- main/plugins/org.talend.mdm.workbench/src/com/amalto/workbench/utils/XmlUtil.java
There are a some instances in the code where toLowerCase().equals() is used, when equalsIgnoreCase() would suffice. The latter is more concise + also doesn't involve the default Locale that's used with toLowerCase(), which might be problematic depending on the String being compared.
> TMDM-14772 Replace toLowerCase().equals() with equalsIgnoreCase

- main/plugins/org.talend.mdm.ws/META-INF/MANIFEST.MF
https://jira.talendforge.org/browse/TUP-26543
Install unziped p2 packages using command won't let mdm webservice connection work
Install unziped p2 packages using command won't let mdm webservice connection work(test with different version jdk: jdk8 & jdk11)
> bugfix(TUP-26543) Specify the required bundle version.

- main/plugins/org.talend.designer.components.tomprovider/components/tMDMConnection/tMDMConnection_java.xml
- main/plugins/org.talend.designer.components.tomprovider/components/tMDMReadConf/tMDMReadConf_java.xml
- main/plugins/org.talend.designer.components.tomprovider/components/tMDMRouteRecord/tMDMRouteRecord_java.xml
- main/plugins/org.talend.designer.components.tomprovider/components/tMDMSP/tMDMSP_java.xml
- main/plugins/org.talend.designer.components.tomprovider/components/tMDMWriteConf/tMDMWriteConf_java.xml
https://jira.talendforge.org/browse/TMDM-14759
If some component include mdm_transaction package, it load the old jar that caused NoClassDefFoundError error.
Update related config file to fix the question.
> TMDM-14759 Remove commons logging from mdm-transaction library

- main/plugins/org.talend.mdm.workbench/src/com/amalto/workbench/widgets/xmleditor/ExtensibleEditorContent.java
https://jira.talendforge.org/browse/TUP-28521
the plugin parameters of plugin type xslt, codec, regexp, replace.... can't be displayed in the editor for process.
the plugin parameters of plugin type  xslt, codec, regexp, replace.... can be displayed in the editor for process.
> feat(TUP-28521) fix problem that plugin editor can't show content for plugins.

- main/plugins/org.talend.mdm.workbench/src/com/amalto/workbench/utils/LocalTreeObjectRepository.java
https://jira.talendforge.org/browse/TUP-29347
"Import Server Objects from MDM server" hangs consuming high CPU when resources contains more data.(like 100 thousands records).
"Import Server Objects from MDM server" will finish in minutes when resources contains more data records.
> fix(TUP-29347) fix displace resource node error during importing server objects.
