Talend/tmdm-studio-se

main/features/org.talend.rcp.branding.tombundle.feature/feature.xml
main/plugins/org.talend.rcp.branding.tombundle/plugin.xml

https://jira.talendforge.org/browse/TUP-2649
hi, Could you help me to merge it into master?

TUP-2649 new feature: Update the following branding plugins to use Talend Theme

---

main/features/org.talend.rcp.branding.tombundle.feature/feature.xml
main/plugins/org.talend.rcp.branding.tombundle/plugin.xml

https://jira.talendforge.org/browse/TUP-2649
Rename plugin name, since the old plugin name can not be loaded into tis

TUP-2649 new feature: Update branding plugins to use Talend Theme

---

main/features/org.talend.rcp.branding.tombundle.feature/feature.xml

https://jira.talendforge.org/browse/TDI-34196
Add on-boarding presentation for DI perspective
Please only merge to master, thanks.

TDI-34196 fix bug: Quick tour: in TOS BD-should better hid the studio quick tour option.

---

pom.xml

DEVOPS-1729 Nexus migration: Update URLs [patch/6.1.1]

---

main/plugins/org.talend.mdm.repository.model/model/MDMServerObject.ecore
main/plugins/org.talend.mdm.repository.model/src/main/java/org/talend/mdm/repository/model/mdmserverobject/matchrule/MatchRuleMapInfoPage.java
main/plugins/org.talend.mdm.repository.model/src/main/java/org/talend/mdm/repository/model/mdmserverobject/matchrule/MatchRulePackage.java
main/plugins/org.talend.mdm.repository.model/src/main/java/org/talend/mdm/repository/model/mdmserverobject/matchrule/impl/MatchRuleMapInfoPageImpl.java
main/plugins/org.talend.mdm.repository.model/src/main/java/org/talend/mdm/repository/model/mdmserverobject/matchrule/impl/MatchRulePackageImpl.java

one match rule definition to one entity.

TMDM-10647: Adapt emf model to apply multiple match rules of

---

main/plugins/org.talend.mdm.repository/src/main/java/org/talend/mdm/repository/core/command/AbstractCommand.java
main/plugins/org.talend.mdm.repository/src/main/java/org/talend/mdm/repository/core/command/CommandManager.java
main/plugins/org.talend.mdm.repository/src/main/java/org/talend/mdm/repository/core/command/CommandStack.java
main/plugins/org.talend.mdm.repository/src/main/java/org/talend/mdm/repository/core/command/ICommand.java
main/plugins/org.talend.mdm.repository/src/main/java/org/talend/mdm/repository/core/command/ICommandManagerExAdapter.java
main/plugins/org.talend.mdm.repository/src/main/java/org/talend/mdm/repository/core/command/deploy/DefaultDeployCommand.java
main/plugins/org.talend.mdm.repository/src/main/java/org/talend/mdm/repository/core/impl/RepositoryNodeActionProviderAdapter.java
main/plugins/org.talend.mdm.repository/src/main/java/org/talend/mdm/repository/core/impl/datamodel/DataModelActionProvider.java
main/plugins/org.talend.mdm.repository/src/main/java/org/talend/mdm/repository/core/service/DeployService.java
main/plugins/org.talend.mdm.workbench/src/com/amalto/workbench/utils/HttpClientUtil.java
main/plugins/org.talend.mdm.workbench/src/com/amalto/workbench/utils/OperationIgnoredException.java

1. Removed the "Create TDS Campaign" from context menu.
2. Deploying TDS get transparent

TMDM-10644: Fixed the following:

---

main/plugins/org.talend.rcp.branding.tombundle/content/root.xhtml

https://jira.talendforge.org/browse/TUP-18946

feat(TUP-18946): add advertisement for Cloud product

---

main/plugins/org.talend.mdm.repository.validate/src/org/talend/mdm/repository/core/marker/IValidationMarker.java
main/plugins/org.talend.mdm.repository.validate/src/org/talend/mdm/repository/core/marker/ValidateMarkerUtil.java
main/plugins/org.talend.mdm.repository.validate/src/org/talend/mdm/repository/core/validate/MDMValidationRunner.java
main/plugins/org.talend.mdm.repository/src/main/java/org/talend/mdm/repository/utils/IRepositoryResourceUtilExAdapter.java
main/plugins/org.talend.mdm.repository/src/main/java/org/talend/mdm/repository/utils/RepositoryResourceUtil.java

https://jira.talendforge.org/browse/TMDM-11810
Can deploy workflow which is imported from local and System role used
Do check workflow if used system role when importing from local and deploy to server.

TMDM-11810 check if system role like System_XXX/administration used in workflow when import from local and deploy to server.

---

main/plugins/org.talend.mdm.repository/src/main/java/org/talend/mdm/repository/utils/IRepositoryResourceUtilExAdapter.java
main/plugins/org.talend.mdm.repository/src/main/java/org/talend/mdm/repository/utils/RepositoryResourceUtil.java

https://jira.talendforge.org/browse/TMDM-11810
Correct wrong PR https://github.com/Talend/tmdm-studio-se/pull/145
format the  code.

TMDM-11810 Deploy workflow failed if System_XXX/administration used (format)

---

main/plugins/org.talend.mdm.repository/src/main/java/org/talend/mdm/repository/core/dnd/RepositoryDropAssistant.java
main/plugins/org.talend.mdm.repository/src/main/java/org/talend/mdm/repository/ui/actions/CreateFolderAction.java
main/plugins/org.talend.mdm.repository/src/main/java/org/talend/mdm/repository/ui/actions/RenameObjectAction.java
main/plugins/org.talend.mdm.repository/src/main/java/org/talend/mdm/repository/utils/ValidateUtil.java
test/plugins/org.talend.mdm.repository.test/src/main/java/org/talend/mdm/repository/utils/ValidateUtilTest.java

https://jira.talendforge.org/browse/TMDM-11566
System role like System_XXX and administration(no matter the case) can be shown in the repository, can be edit by user.
System folder 'System' can be shown in the repository.
System role like System_XXX and administration(no matter the case) and system folder 'System' can not be shown in the repository, also can not be imported.

TMDM-11566 Dis-allow create system role,system folder of role, dis-allow update to system role.

---

main/plugins/org.talend.mdm.workbench/src/com/amalto/workbench/editors/AFormPage.java

https://jira.talendforge.org/browse/TUP-19969

fix(TUP-19969): Eclipse upgrade - TOS need to work with eclipse 4.7.0

---

main/features/org.talend.mdm.tom.test.feature/feature.xml
main/plugins/org.talend.mdm.repository/src/main/java/org/talend/mdm/repository/utils/ServiceUtil.java

Studio upgrade/eclipse 4.7.0

---

main/plugins/org.talend.mdm.repository/src/main/java/org/talend/mdm/repository/core/command/CommandManager.java

link: https://jira.talendforge.org/browse/TMDM-11548
Deploy a workflow successfully but in message will show deploy failed if deploy it failed before.
Show successful information when deploy successfully .

TMDM-11548:Deploy a workflow successfully but in message will show deploy failed if deploy it failed before.

---

main/plugins/org.talend.mdm.repository/src/main/java/org/talend/mdm/repository/core/dnd/RepositoryDropAssistant.java
main/plugins/org.talend.mdm.repository/src/main/java/org/talend/mdm/repository/ui/actions/RenameObjectAction.java
main/plugins/org.talend.mdm.repository/src/main/java/org/talend/mdm/repository/ui/wizards/MdmPropertiesWizard.java
main/plugins/org.talend.mdm.repository/src/main/java/org/talend/mdm/repository/utils/ValidateUtil.java
test/plugins/org.talend.mdm.repository.test/src/main/java/org/talend/mdm/repository/utils/ValidateUtilTest.java

https://jira.talendforge.org/browse/TMDM-12056
Does not show right message if input invalid character for role name.
Show right message for input invalid character and system role pattern string.

TMDM-11566 Both judge invalid character and system role.

---

main/plugins/org.talend.mdm.repository/src/main/java/org/talend/mdm/repository/ui/actions/job/RunProcessAction.java

https://jira.talendforge.org/browse/TUP-20166

fix(TUP-20166): Studio "Attempted to beginRule: F/.Java/src/main/java, does not match outer scope rule" Error

---

main/plugins/org.talend.mdm.ws/src/com/amalto/workbench/webservices/WSPutItemWithReport.java

https://jira.talendforge.org/browse/TMDM-10163
webservice stub class is not synchronized to server side.
Synchronize webservice stub class.

TMDM-10163 Before Save Process to return a warning message

---

main/plugins/org.talend.mdm.workbench/src/com/amalto/workbench/editors/DataModelMainPage.java
main/plugins/org.talend.mdm.workbench/src/com/amalto/workbench/utils/XSDAnnotationsStructure.java

link: https://jira.talendforge.org/browse/TMDM-12228
1.Can not pop correct write access dialog when double click X_Write annotation.
2.No response when double click  X_No_Add and X_No_Remove annotation
1. Fixed can not pop correct write access dialog when double click X_Write annotation.
2. Add "double click" action for new X_No_Add and X_No_Remove annotation.

TMDM-10617  Add the function to disable Add and enable Remove button for a FK field

---

test/plugins/org.talend.mdm.repository.test/src/main/java/org/talend/mdm/repository/core/service/ConsistencyServiceTest.java

https://jira.talendforge.org/browse/TMDM-12391
test fail, random UnfinishedVerificationException in test method testUpdateCurrentDigestValue.
run unit test success
fix test failure

TMDM-12391 Correct method call, fix unit test random fail .

---

main/plugins/org.talend.mdm.repository/src/main/java/org/talend/mdm/repository/core/dnd/RepositoryDropAssistant.java

https://jira.talendforge.org/browse/TMDM-11790
Drag/Drop view sometimes can not drag to sub category.
Drag/Drop view can work normally.

TMDM-11790 Make view contained in a Category can be drag/drop to other category of same type.

---

main/plugins/org.talend.mdm.workbench/src/com/amalto/workbench/editors/ViewBrowserMainPage.java

https://jira.talendforge.org/browse/TMDM-12487
Remove duplication search option of "Full-Text".

TMDM-12486 Remove duplication search option of "Full-Text".

---

main/plugins/org.talend.mdm.repository/src/main/java/org/talend/mdm/repository/ui/editors/ISvnGitHistory.java
main/plugins/org.talend.mdm.repository/src/main/java/org/talend/mdm/repository/ui/editors/XObjectBrowser2.java
main/plugins/org.talend.mdm.repository/src/main/java/org/talend/mdm/repository/ui/editors/XObjectEditor2.java
main/plugins/org.talend.mdm.repository/src/main/java/org/talend/mdm/repository/ui/editors/XSDEditor2.java

https://jira.talendforge.org/browse/TMDM-10441
Update interface name.

TMDM-10441 Adapter the class name.

---

main/plugins/org.talend.designer.components.tomprovider/components/tMDMConnection/tMDMConnection_java.xml
main/plugins/org.talend.designer.components.tomprovider/components/tMDMDelete/tMDMDelete_java.xml
main/plugins/org.talend.designer.components.tomprovider/components/tMDMOutput/tMDMOutput_java.xml
main/plugins/org.talend.designer.components.tomprovider/components/tMDMReadConf/tMDMReadConf_java.xml
main/plugins/org.talend.designer.components.tomprovider/components/tMDMRouteRecord/tMDMRouteRecord_java.xml
main/plugins/org.talend.designer.components.tomprovider/components/tMDMSP/tMDMSP_java.xml
main/plugins/org.talend.designer.components.tomprovider/components/tMDMTriggerInput/tMDMTriggerInput_java.xml
main/plugins/org.talend.designer.components.tomprovider/components/tMDMTriggerOutput/tMDMTriggerOutput_java.xml
main/plugins/org.talend.designer.components.tomprovider/components/tMDMViewSearch/tMDMViewSearch_java.xml
main/plugins/org.talend.designer.components.tomprovider/components/tMDMWriteConf/tMDMWriteConf_java.xml
main/plugins/org.talend.mdm.repository/plugin.xml

chore(TUP-20636) update maven uri

---

main/plugins/org.talend.mdm.repository/src/main/java/org/talend/mdm/repository/utils/RepositoryResourceUtil.java

Thowing NPE when recreate data model with different case
link: https://jira.talendforge.org/browse/TMDM-12553
no exception is thrown.

TMDM-12553  Recreate data model throw errors

---

main/plugins/org.talend.mdm.workbench/src/com/amalto/workbench/detailtabs/sections/CommitBarListenerSection.java
main/plugins/org.talend.mdm.workbench/src/com/amalto/workbench/detailtabs/sections/handlers/ElementForeighKeyCommitHandler.java
main/plugins/org.talend.mdm.workbench/src/com/amalto/workbench/detailtabs/sections/handlers/ElementWrapperCommitHandler.java
main/plugins/org.talend.mdm.workbench/src/com/amalto/workbench/detailtabs/sections/util/CommitBarListenerRegistry.java

Additional annotations are appended when switch element between FK and reference
link: https://jira.talendforge.org/browse/TMDM-12614
No annotations are appended when switch element between FK and reference

TMDM-12614  Additional annotations are appended when switch element between FK and reference

---

main/plugins/org.talend.mdm.workbench/src/com/amalto/workbench/detailtabs/sections/ElementFKSection.java
main/plugins/org.talend.mdm.workbench/src/com/amalto/workbench/detailtabs/sections/composites/FKIntegrityComposite.java

Show error dialog when switch element between FK and reference.
link: https://jira.talendforge.org/browse/TMDM-12612
No error dialog and exception are thrown  when switch element between FK and reference.

TMDM-12612  Show error dialog when switch element between FK and reference.

---

test/plugins/org.talend.mdm.repository.test/src/main/java/org/talend/mdm/repository/core/service/ConsistencyServiceTest.java

Just backport the fix codes from master to 7.0.
https://jira.talendforge.org/browse/TMDM-12391

TMDM-12391 Fix the "ConsistencyServiceTest" JUnit test fail.

---

main/plugins/org.talend.rcp.branding.tombundle/tombundle.product

https://jira.talendforge.org/browse/TUP-21137

Fix : TUP-21137 Security: jtds-1.3.1-patch.jar ntlmauth loaded from a path variable

---

main/plugins/org.talend.mdm.repository.validate/META-INF/MANIFEST.MF
main/plugins/org.talend.mdm.repository.validate/src/org/talend/mdm/repository/core/validate/i18n/Messages.java
main/plugins/org.talend.mdm.repository.validate/src/org/talend/mdm/repository/core/validate/i18n/messages.properties
main/plugins/org.talend.mdm.repository.validate/src/org/talend/mdm/repository/core/validate/i18n/messages_en.properties
main/plugins/org.talend.mdm.repository.validate/src/org/talend/mdm/repository/core/validate/view/ViewValidator.java
main/plugins/org.talend.mdm.repository/src/main/java/org/talend/mdm/repository/ui/widgets/UserVarValueValidator.java
main/plugins/org.talend.mdm.workbench/src/com/amalto/workbench/utils/Util.java

https://jira.talendforge.org/browse/TMDM-12841
when view condition operator is "Is Empty Or Null", value is allow as other operators
when view condition operator is "Is Empty Or Null", value is not allowed.

TMDM-12841 Don't allow redundant value for operator "Is Empty Or Null" in view's where condition.

---

main/features/org.talend.mdm.tom.test.feature/feature.xml
main/plugins/org.talend.mdm.repository.validate/src/org/talend/mdm/repository/core/validate/view/ViewValidator.java
main/plugins/org.talend.mdm.repository/src/main/java/org/talend/mdm/repository/ui/widgets/UserVarValueValidator.java
pom.xml
test/plugins/org.talend.mdm.repository.test/.settings/org.eclipse.jdt.core.prefs
test/plugins/org.talend.mdm.repository.test/src/main/java/org/talend/mdm/repository/ui/widgets/UserVarValueValidatorTest.java
test/plugins/org.talend.mdm.repository.validate.test/.classpath
test/plugins/org.talend.mdm.repository.validate.test/META-INF/MANIFEST.MF
test/plugins/org.talend.mdm.repository.validate.test/build.properties
test/plugins/org.talend.mdm.repository.validate.test/pom.xml
test/plugins/org.talend.mdm.repository.validate.test/src/main/java/org/talend/mdm/repository/core/validate/view/ViewValidatorTest.java
test/plugins/org.talend.mdm.workbench.test/src/main/java/com/amalto/workbench/utils/UtilTest.java

https://jira.talendforge.org/browse/TMDM-12841
Add unit test.
Add unit test.

TMDM-12841 Add unit test.

---

main/plugins/org.talend.designer.routines.mdmprovider/resources/java/routines/MDM.java

https://jira.talendforge.org/browse/TUP-21263

TUP-21263 Consider setting the secure processing feature on XPathFactory instances

---

main/plugins/org.talend.designer.routines.mdmprovider/resources/java/routines/MDM.java
main/plugins/org.talend.mdm.workbench/src/com/amalto/workbench/utils/Util.java
main/plugins/org.talend.mdm.workbench/src/com/amalto/workbench/utils/XSDGenerateHTML.java
main/plugins/org.talend.mdm.workbench/src/com/amalto/workbench/utils/XSDParser.java
main/plugins/org.talend.mdm.workbench/src/com/amalto/workbench/utils/XmlUtil.java

https://jira.talendforge.org/browse/TUP-21305

Fix TUP-21305 Set the secure processing feature on TransformerFactory instances

---

test/plugins/org.talend.mdm.repository.validate.test/src/main/java/org/talend/mdm/repository/core/validate/view/ViewValidatorTest.java

ClassNotFoundException: org.mockito.internal.util.reflection.Whitebox for unit test.

TMDM-12841 fix unit test.

---

main/plugins/org.talend.mdm.repository/src/main/java/org/talend/mdm/repository/utils/RepositoryResourceUtil.java
test/plugins/org.talend.mdm.repository.test/src/main/java/org/talend/mdm/repository/utils/RepositoryResourceUtilTest.java

https://jira.talendforge.org/browse/TMDM-12383
Deployment on commandline does not support deploy specified version object.
Support deploy specified version object to server on commandline.

TMDM-12383 Find the specified version object and return version infos.

---

main/plugins/org.talend.mdm.repository/src/main/java/org/talend/mdm/repository/ui/navigator/IPerspectiveConstants.java
main/plugins/org.talend.mdm.repository/src/main/java/org/talend/mdm/repository/utils/ServiceUtil.java
main/plugins/org.talend.mdm.repository/src/main/java/org/talend/mdm/repository/utils/UIUtil.java
main/plugins/org.talend.mdm.workbench/src/com/amalto/workbench/editors/AFormPage.java
main/plugins/org.talend.mdm.workbench/src/com/amalto/workbench/utils/HttpClientUtil.java
main/plugins/org.talend.rcp.branding.tombundle/META-INF/MANIFEST.MF

This PR is used to record Bonita upgrade, all upgrade codes will commit to this branch.
TMDM-12930:  After upgrade to Eclipse 4.7, the SE repository has many compilation errors
link:
https://jira.talendforge.org/browse/TMDM-11527 (Upgrade to Bonita 7.8) 
https://jira.talendforge.org/browse/TMDM-12930 (last PR)
TMDM-12930: 
1. Fixed compilation error caused by upgrading to Eclipse 4.7.
2. Remove deprecated Bonita form perspective definition
3. Improve "isWorkInUI" function based on Eclipse 4.7
If this PR contains a breaking change, …

TMDM-11527  Upgrade to Bonita 7.8

---

main/plugins/org.talend.designer.components.tomprovider/components/tMDMConnection/tMDMConnection_java.xml
main/plugins/org.talend.designer.components.tomprovider/components/tMDMDelete/tMDMDelete_java.xml
main/plugins/org.talend.designer.components.tomprovider/components/tMDMOutput/tMDMOutput_java.xml
main/plugins/org.talend.designer.components.tomprovider/components/tMDMReadConf/tMDMReadConf_java.xml
main/plugins/org.talend.designer.components.tomprovider/components/tMDMRouteRecord/tMDMRouteRecord_java.xml
main/plugins/org.talend.designer.components.tomprovider/components/tMDMSP/tMDMSP_java.xml
main/plugins/org.talend.designer.components.tomprovider/components/tMDMViewSearch/tMDMViewSearch_java.xml
main/plugins/org.talend.designer.components.tomprovider/components/tMDMWriteConf/tMDMWriteConf_java.xml

Jira: https://jira.talendforge.org/browse/TMDM-13196
current JAR's version:
CXF: 3.2.6
woodstox-core: 5.1.0
xmlschema-core:2.2.3
Updated to:
CXF: 3.3.0
woodstox-core: 5.2.0
xmlschema-core:2.2.4

TMDM-13196 Upgrade to CXF 3.3.0 (MDM)

---

main/plugins/org.talend.designer.components.tomprovider/components/tMDMConnection/tMDMConnection_java.xml
main/plugins/org.talend.designer.components.tomprovider/components/tMDMDelete/tMDMDelete_java.xml
main/plugins/org.talend.designer.components.tomprovider/components/tMDMOutput/tMDMOutput_java.xml
main/plugins/org.talend.designer.components.tomprovider/components/tMDMReadConf/tMDMReadConf_java.xml
main/plugins/org.talend.designer.components.tomprovider/components/tMDMRouteRecord/tMDMRouteRecord_java.xml
main/plugins/org.talend.designer.components.tomprovider/components/tMDMSP/tMDMSP_java.xml
main/plugins/org.talend.designer.components.tomprovider/components/tMDMViewSearch/tMDMViewSearch_java.xml
main/plugins/org.talend.designer.components.tomprovider/components/tMDMWriteConf/tMDMWriteConf_java.xml

Reverts Talend/tmdm-studio-se#246

Revert "TMDM-13196 Upgrade to CXF 3.3.0 (MDM)"

---

main/plugins/org.talend.designer.routines.mdmprovider/META-INF/MANIFEST.MF
main/plugins/org.talend.mdm.repository.validate/src/org/talend/mdm/repository/core/validate/MDMValidationRunner.java
main/plugins/org.talend.mdm.repository/src/main/java/org/talend/mdm/repository/ui/navigator/IPerspectiveConstants.java
main/plugins/org.talend.mdm.repository/src/main/java/org/talend/mdm/repository/utils/ServiceUtil.java
main/plugins/org.talend.mdm.repository/src/main/java/org/talend/mdm/repository/utils/UIUtil.java
main/plugins/org.talend.mdm.workbench.serverexplorer/src/main/java/org/talend/mdm/workbench/serverexplorer/console/MDMServerConsoleFactory.java
main/plugins/org.talend.mdm.workbench/src/com/amalto/workbench/editors/AFormPage.java
main/plugins/org.talend.mdm.workbench/src/com/amalto/workbench/utils/HttpClientUtil.java
main/plugins/org.talend.mdm.workbench/src/com/amalto/workbench/widgets/ValidationRuleWidget.java
main/plugins/org.talend.rcp.branding.tombundle/META-INF/MANIFEST.MF

https://jira.talendforge.org/browse/TUP-18064

Studio upgrade/eclipse 4.10.0

---

main/plugins/org.talend.designer.components.tomprovider/components/tMDMOutput/tMDMOutput_main.javajet
main/plugins/org.talend.designer.components.tomprovider/components/tMDMWriteConf/tMDMWriteConf_main.javajet

Throw exception when return keys is null in tMDMOutput
Added a condition, if nothing updated, return keys column is null.

TMDM-13190 tMDMOutput / Is Update / Return Keys : java.lang.IndexOutOfBoundsException: Index: 0, Size: 0 if nothing to update

---

main/plugins/org.talend.designer.components.tomprovider/components/tMDMConnection/tMDMConnection_java.xml
main/plugins/org.talend.designer.components.tomprovider/components/tMDMDelete/tMDMDelete_java.xml
main/plugins/org.talend.designer.components.tomprovider/components/tMDMOutput/tMDMOutput_java.xml
main/plugins/org.talend.designer.components.tomprovider/components/tMDMReadConf/tMDMReadConf_java.xml
main/plugins/org.talend.designer.components.tomprovider/components/tMDMRouteRecord/tMDMRouteRecord_java.xml
main/plugins/org.talend.designer.components.tomprovider/components/tMDMSP/tMDMSP_java.xml
main/plugins/org.talend.designer.components.tomprovider/components/tMDMViewSearch/tMDMViewSearch_java.xml
main/plugins/org.talend.designer.components.tomprovider/components/tMDMWriteConf/tMDMWriteConf_java.xml

Jira: https://jira.talendforge.org/browse/TMDM-13196
current JAR's version:
CXF: 3.2.6
woodstox-core: 5.1.0
xmlschema-core:2.2.3
Updated to:
CXF: 3.3.1
woodstox-core: 5.2.0
xmlschema-core:2.2.4

TMDM-13196 Upgrade to CXF 3.3.1 (MDM)

---

main/plugins/org.talend.mdm.engines.client/src/org/talend/mdm/engines/client/ui/wizards/DeployOnMDMExportWizard.java

https://jira.talendforge.org/browse/TMDM-13299
Deploy a job to MDM Server failed with NPE.
Deploy a job to MDM Server successfully.

TMDM-13299 Fix NPE found while deploy job to MDM Server.

---

main/plugins/org.talend.mdm.ws.jars/.project

Missing .project file.
Add back.

TMDM-13363 Add .project file.

---

main/plugins/org.talend.mdm.repository/src/main/java/org/talend/mdm/repository/core/service/IRemoveViewObjectService.java
main/plugins/org.talend.mdm.repository/src/main/java/org/talend/mdm/repository/ui/actions/recyclebin/AbstractRemoveCommandStackAction.java

https://jira.talendforge.org/browse/TMDM-13313
Create a workflow with form, duplicate it, delete the duplicate workflow, empty the recycle bin, form file(s) removed also .
Create a workflow with form, duplicate it, delete the duplicate workflow, empty the recycle bin, form file(s) will be kept .

TMDM-13313 Fix delete workflow problem introduced by form shared by multiple workflows.

---

test/plugins/org.talend.mdm.repository.test/src/main/java/org/talend/mdm/repository/core/service/ConsistencyServiceTest.java
test/plugins/org.talend.mdm.repository.test/src/main/java/org/talend/mdm/repository/core/service/ContainerCacheServiceTest.java
test/plugins/org.talend.mdm.repository.test/src/main/java/org/talend/mdm/repository/core/service/DeployServiceTest.java
test/plugins/org.talend.mdm.repository.test/src/main/java/org/talend/mdm/repository/ui/actions/AbstractSimpleAddActionTest.java
test/plugins/org.talend.mdm.repository.test/src/main/java/org/talend/mdm/repository/ui/actions/RemoveFromRepositoryActionTest.java
test/plugins/org.talend.mdm.repository.test/src/main/java/org/talend/mdm/repository/ui/actions/RenameObjectActionTest.java
test/plugins/org.talend.mdm.repository.test/src/main/java/org/talend/mdm/repository/utils/Bean2EObjUtilTest.java
test/plugins/org.talend.mdm.repository.test/src/main/java/org/talend/mdm/repository/utils/BeanClassUtilTest.java
test/plugins/org.talend.mdm.repository.test/src/main/java/org/talend/mdm/repository/utils/RepositoryResourceUtilTest.java
test/plugins/org.talend.mdm.repository.test/src/main/java/org/talend/mdm/repository/utils/ValidateUtilTest.java
test/plugins/org.talend.mdm.workbench.test/src/main/java/com/amalto/workbench/utils/PasswordUtilTest.java
test/plugins/org.talend.mdm.workbench.test/src/main/java/com/amalto/workbench/utils/UtilMockTest.java

TUP-22672 upgrade jars for powermock after running Junit cases with

---

main/plugins/org.talend.mdm.repository/src/main/java/org/talend/mdm/repository/ui/wizards/imports/ImportServerObjectWizard.java
main/plugins/org.talend.mdm.repository/src/main/java/org/talend/mdm/repository/utils/RepositoryResourceUtil.java

https://jira.talendforge.org/browse/TMDM-13312
https://jira.talendforge.org/browse/TMDM-13315
Create a workflow then rename it in Bonita perspective will show 2 diagrams editors.
Rename a workflow from Bonita perspective will disappear in MDM workflow list
Rename it in Bonita perspective will open correct editor and respond correct in mdm perspective.

TMDM-13312 Add api to get any version object by resource file.

---

main/plugins/org.talend.mdm.repository/src/main/java/org/talend/mdm/repository/core/IRepositoryNodeResourceProvider.java
main/plugins/org.talend.mdm.repository/src/main/java/org/talend/mdm/repository/core/impl/AbstractRepositoryNodeResourceProvider.java
main/plugins/org.talend.mdm.repository/src/main/java/org/talend/mdm/repository/ui/actions/recyclebin/AbstractRemoveCommandStackAction.java
main/plugins/org.talend.mdm.repository/src/main/java/org/talend/mdm/repository/utils/RepositoryResourceUtil.java

https://jira.talendforge.org/browse/TMDM-13315
Delete multi version workflow in mdm recycle bin will not delete all file in bonita project.
Delete multi version workflow in mdm recycle bin also will delete all file in bonita project.

TMDM-13315 Delete all versions of select object when do delete action in mdm repository view.

---

main/plugins/org.talend.designer.components.tomprovider/components/tMDMBulkLoad/tMDMBulkLoad_java.xml
main/plugins/org.talend.designer.components.tomprovider/components/tMDMConnection/tMDMConnection_java.xml
main/plugins/org.talend.designer.components.tomprovider/components/tMDMDelete/tMDMDelete_java.xml
main/plugins/org.talend.designer.components.tomprovider/components/tMDMOutput/tMDMOutput_java.xml
main/plugins/org.talend.designer.components.tomprovider/components/tMDMReadConf/tMDMReadConf_java.xml
main/plugins/org.talend.designer.components.tomprovider/components/tMDMRouteRecord/tMDMRouteRecord_java.xml
main/plugins/org.talend.designer.components.tomprovider/components/tMDMSP/tMDMSP_java.xml
main/plugins/org.talend.designer.components.tomprovider/components/tMDMTriggerInput/tMDMTriggerInput_java.xml
main/plugins/org.talend.designer.components.tomprovider/components/tMDMTriggerOutput/tMDMTriggerOutput_java.xml
main/plugins/org.talend.designer.components.tomprovider/components/tMDMViewSearch/tMDMViewSearch_java.xml
main/plugins/org.talend.designer.components.tomprovider/components/tMDMWriteConf/tMDMWriteConf_java.xml

Jira: https://jira.talendforge.org/browse/TMDM-13423
below components don't support java11.
1. tMDMRouteRecord
2. tMDMTriggerinput
3. tMDMTriggerOutput
4. tMDMViewSearch
5. tMDMBulkload
6. tMDMSP
7. tMDMConnection
8. tMDMReadConf
9. tMDMWriteConf
10. tMDMDelete
Add the dependency jar:
```
<IMPORT
NAME="javax.annotation-api-1.3"
MODULE="javax.annotation-api-1.3.jar"
MVN="mvn:javax.annotation/javax.annotation-api/1.3"
REQUIRED="true"
BundleID=""
/>
<IMPORT
NAME="jaxb-api-2.3.0"
MODULE="jaxb-api-2.3.0.jar"
MVN="mvn:javax.xml.bind/jaxb-api/2.3.0"
REQUIRED="true"
BundleID=""
/>
<IMPORT
NAME="jsr181-api-1.0-MR1"
MODULE="jsr181-api-1.0-MR1.jar"
MVN="mvn:javax.jws/jsr181-api/1.0-MR1" …
```

TMDM-13423 Compile error when run MDM demo jobs (java 11)

---

main/plugins/org.talend.mdm.repository.validate/src/org/talend/mdm/repository/core/validate/MDMValidationRunner.java
main/plugins/org.talend.mdm.repository/src/main/java/org/talend/mdm/repository/core/service/DeployService.java
main/plugins/org.talend.mdm.repository/src/main/java/org/talend/mdm/repository/ui/actions/DeployAllAction.java
main/plugins/org.talend.mdm.repository/src/main/java/org/talend/mdm/repository/ui/actions/DeployAnotherVersionAction.java
main/plugins/org.talend.mdm.repository/src/main/java/org/talend/mdm/repository/ui/actions/DeployToAction.java
main/plugins/org.talend.mdm.repository/src/main/java/org/talend/mdm/repository/ui/actions/DeployToLastServerAction.java
main/plugins/org.talend.mdm.repository/src/main/java/org/talend/mdm/repository/ui/actions/RemoveFromServerAction.java
main/plugins/org.talend.mdm.repository/src/main/java/org/talend/mdm/repository/ui/editors/XSDEditor2.java

1. Throwing exception when saving "DataModel" object.
2. Popup two validation dialog when deploying an unsaved DataModel object.
link: https://jira.talendforge.org/browse/TMDM-13298
Fixed above errors.

TMDM-13298 "Set the WorkFlow Access" on entity after saving will show error in error log

---

main/plugins/org.talend.mdm.repository.validate/src/org/talend/mdm/repository/core/validate/MDMValidationRunner.java
main/plugins/org.talend.mdm.repository.validate/src/org/talend/mdm/repository/core/validate/MDMValidationService.java
main/plugins/org.talend.mdm.repository/src/main/java/org/talend/mdm/repository/core/service/DeployService.java
main/plugins/org.talend.mdm.repository/src/main/java/org/talend/mdm/repository/core/service/IModelValidationService.java
main/plugins/org.talend.mdm.repository/src/main/java/org/talend/mdm/repository/ui/actions/AbstractDeployAction.java
main/plugins/org.talend.mdm.repository/src/main/java/org/talend/mdm/repository/ui/actions/DeployAllAction.java
main/plugins/org.talend.mdm.repository/src/main/java/org/talend/mdm/repository/ui/actions/DeployAnotherVersionAction.java
main/plugins/org.talend.mdm.repository/src/main/java/org/talend/mdm/repository/ui/actions/DeployToAction.java
main/plugins/org.talend.mdm.repository/src/main/java/org/talend/mdm/repository/ui/actions/DeployToLastServerAction.java
main/plugins/org.talend.mdm.repository/src/main/java/org/talend/mdm/repository/ui/actions/RemoveFromServerAction.java
main/plugins/org.talend.mdm.repository/src/main/java/org/talend/mdm/repository/ui/actions/ValidateAction.java
main/plugins/org.talend.mdm.repository/src/main/java/org/talend/mdm/repository/ui/editors/XSDEditor2.java

https://jira.talendforge.org/browse/TMDM-13548
Do deployment of mdm items will always failed under Linux platform. Because on Unix like platform, it's not allowed to re-generate Display class's instance for application, if do so SWTError will be thrown, then cause the deployment failure.
Can do deployment/import from DI without that error, can save data model without error.

TMDM-13548 NullPointerException occured while do some basic actions(Linux Platform)

---

main/plugins/org.talend.mdm.repository/src/main/java/org/talend/mdm/repository/ui/wizards/MDMOpenExistVersionProcessWizard.java

Open another version of workflow failed with form on ubuntu 18.
link: https://jira.talendforge.org/browse/TMDM-13639
The workflow can be created and opened on ubuntu 18.

TMDM-13639  Open another version of workflow failed with form on ubuntu 18.

---

main/plugins/org.talend.mdm.repository/src/main/java/org/talend/mdm/repository/ui/wizards/MDMOpenExistVersionProcessWizard.java

This is a backport PR for https://github.com/Talend/tmdm-studio-se/pull/283

    TMDM-13639  Open another version of workflow failed with form on ubuntu 18

---

main/plugins/org.talend.mdm.repository.validate/src/org/talend/mdm/repository/core/validate/MDMValidationRunner.java

https://jira.talendforge.org/browse/TMDM-13640
Sometimes deadlock will happen during handling workflow.
Resolved Thread deadlock.

TMDM-13640 Add schedule rule to validation.

---

main/plugins/org.talend.mdm.repository/src/main/java/org/talend/mdm/repository/core/service/DeployService.java

https://jira.talendforge.org/browse/TMDM-11940
During cmdline test found some deploy command has not link repository view object, this lead to test fail.
Remove invalid deploy command that does not linked repository view object.

TMDM-11940 filter out invalid deploy command that hasn't link repository view object , this found when executing cmdline test.

---

main/plugins/org.talend.mdm.workbench.serverexplorer/src/main/java/org/talend/mdm/workbench/serverexplorer/console/MDMServerLogMessageConsole.java
main/plugins/org.talend.mdm.workbench.serverexplorer/src/main/java/org/talend/mdm/workbench/serverexplorer/console/MDMServerMessageConsole.java
main/plugins/org.talend.mdm.workbench.serverexplorer/src/main/java/org/talend/mdm/workbench/serverexplorer/i18n/Messages.java
main/plugins/org.talend.mdm.workbench.serverexplorer/src/main/java/org/talend/mdm/workbench/serverexplorer/i18n/messages.properties

https://jira.talendforge.org/browse/TMDM-13102
There is a security risk as the fileName could contain ".." characters to break out of the output file path.
For security risk reason, if extracted filename contains invalid char "..", set default file name to value that according to corresponding to current log.

TMDM-13102 Validate filename in MDMServerMessageConsole

---

main/features/org.talend.rcp.branding.tombundle.feature/feature.xml

https://jira.talendforge.org/browse/TMDM-13739
In file feature.xml exist duplicated org.talend.libraries.mdm.webservice.ce .
Remove duplicated one.

TMDM-13739 Remove duplicated 'org.talend.libraries.mdm.webservice.ce' from feature's plugin list.

---

main/plugins/org.talend.mdm.workbench/src/com/amalto/workbench/editors/ViewMainPage.java
main/plugins/org.talend.mdm.workbench/src/com/amalto/workbench/i18n/Messages.java
main/plugins/org.talend.mdm.workbench/src/com/amalto/workbench/i18n/messages.properties
main/plugins/org.talend.mdm.workbench/src/com/amalto/workbench/utils/Util.java

The following function doesn't work when studio switching to non-English language.
1.  'Set write access to role' or 'set no access to role'
2.  Change PK info
3.   Change lookup field
link: https://jira.talendforge.org/browse/TMDM-13744
Fixed above bugs.

TMDM-13744 Not possible to change PK info fields in Studio

---

main/plugins/org.talend.mdm.repository/src/main/java/org/talend/mdm/repository/ui/actions/RemoveFromRepositoryAction.java
test/plugins/org.talend.mdm.repository.test/src/main/java/org/talend/mdm/repository/ui/actions/RemoveFromRepositoryActionTest.java

https://jira.talendforge.org/browse/TMDM-13277
Junit test failed becaused missing third party libararries on Unix like OS, caused by powermock on jface classes.
fix the junit test.

TMDM-13277 fix unit test failure in linux os.

---

main/plugins/org.talend.mdm.workbench/src/com/amalto/workbench/widgets/FilteredCheckboxTree.java

https://jira.talendforge.org/browse/TUP-23854

fix(TUP-23854)Can't create EDI until I open error log view

---

main/plugins/org.talend.mdm.repository.validate/src/org/talend/mdm/repository/core/validate/MDMValidationRunner.java

https://jira.talendforge.org/browse/TMDM-13834
When bpm feature is not installed, import mdm demo project will not import objects as expected and shows error dialog.
Can import all items in mdm demo project without error dialog shows.

TMDM-13834 handle exception throws by finding reference file.

---

main/plugins/org.talend.mdm.repository/resources/system/datamodel/UpdateReport_0.1.xsd
main/plugins/org.talend.mdm.repository/src/main/java/org/talend/mdm/repository/ui/wizards/imports/DataModelSchemaUpdator.java
test/plugins/org.talend.mdm.repository.test/src/main/java/org/talend/mdm/repository/ui/wizards/imports/DataModelSchemaUpdatorTest.java
test/plugins/org.talend.mdm.repository.test/temp/UpdateReport.xsd

- No PrimaryKeyInfo field for Journal
- Add new field of PrimaryKeyInfo field for Journal

TMDM-12997 Add more fields in the Jounal from the MDM Web UI

---

main/plugins/org.talend.designer.components.tomprovider/components/tMDMDelete/tMDMDelete_java.xml
main/plugins/org.talend.designer.components.tomprovider/components/tMDMViewSearch/tMDMViewSearch_java.xml

JIRA: https://jira.talendforge.org/browse/TMDM-13886
tMDMViewSearch and tMDMDelete run failed on JDK 11 without tMDMconnection
add the **activation.jar** for the two components.

TMDM-13886 tMDMViewSearch and tMDMDelete run failed on JDK 11 without tMDMconnection

---

main/plugins/org.talend.mdm.workbench/src/com/amalto/workbench/models/IAnnotationConst.java
main/plugins/org.talend.mdm.workbench/src/com/amalto/workbench/utils/XSDAnnotationsStructure.java
main/plugins/org.talend.mdm.workbench/src/com/amalto/workbench/utils/XSDUtil.java
test/plugins/org.talend.mdm.workbench.test/src/main/java/com/amalto/workbench/utils/CategoryTest.java
test/plugins/org.talend.mdm.workbench.test/src/main/java/com/amalto/workbench/utils/TestCategory01.xsd
test/plugins/org.talend.mdm.workbench.test/src/main/java/com/amalto/workbench/utils/TestCategory02.xsd

Current API does not support for editing "Category"
link: https://jira.talendforge.org/browse/TMDM-13896
Provide support for "Category" annotation in the studio side

TMDM-13896  [Studio] Update API to support "Category" annotation

---

main/plugins/org.talend.mdm.workbench/src/com/amalto/workbench/actions/XSDDeleteParticleAction.java
main/plugins/org.talend.mdm.workbench/src/com/amalto/workbench/utils/XSDUtil.java
test/plugins/org.talend.mdm.workbench.test/.settings/org.eclipse.jdt.core.prefs
test/plugins/org.talend.mdm.workbench.test/src/main/java/com/amalto/workbench/utils/TestCategory03.xsd
test/plugins/org.talend.mdm.workbench.test/src/main/java/com/amalto/workbench/utils/XSDUtilTest.java

https://jira.talendforge.org/browse/TMDM-13981
Synchronize "Category" annotation after deleting a "field" from entity

TMDM-13981 [Studio] Synchronize "Category" annotation after deleting a "field" from entity

---

main/plugins/org.talend.mdm.workbench/src/com/amalto/workbench/dialogs/AnnotationLanguageLabelsDialog.java
main/plugins/org.talend.mdm.workbench/src/com/amalto/workbench/editors/DataModelMainPage.java
main/plugins/org.talend.mdm.workbench/src/com/amalto/workbench/editors/IDataModelMainPageExAdapter.java
test/plugins/org.talend.mdm.workbench.test/src/main/java/com/amalto/workbench/utils/CategoryTest.java

There is no UI to create or edit "Category" annotation.
link: https://jira.talendforge.org/browse/TMDM-13898
Provide a new context menu item and dialog for it.

TMDM-13898  [Studio] Create and Edit "Category" annotation for entity.

---

main/plugins/org.talend.mdm.workbench/src/com/amalto/workbench/dialogs/AnnotationLanguageLabelsDialog.java
main/plugins/org.talend.mdm.workbench/src/com/amalto/workbench/utils/XSDAnnotationsStructure.java
test/plugins/org.talend.mdm.workbench.test/src/main/java/com/amalto/workbench/utils/CategoryTest.java
test/plugins/org.talend.mdm.workbench.test/src/main/java/com/amalto/workbench/utils/TestCategory04.xsd

Throwing NPE when clicking delete button but no item is selected.
link: https://jira.talendforge.org/browse/TMDM-13899
1. Fix throws NPE when clicking delete button but no item is selected.
2. Adjust UI layout to avoid text control is stretched when dialog is resized
3. Fixed delete all field definitions when renaming a category

TMDM-13899  [Studio] Set "Category" annotation for field

---

main/plugins/org.talend.mdm.demo/resources/demoprojects/MDM_CE_DEMOS/metadata/MDMServerDef/My Server_0.1.item
main/plugins/org.talend.mdm.workbench.serverexplorer/plugin.xml
main/plugins/org.talend.mdm.workbench.serverexplorer/src/main/java/org/talend/mdm/workbench/serverexplorer/migration/UnifyPasswordEncryption4MDMServerDefMigrationTask.java
main/plugins/org.talend.mdm.workbench.serverexplorer/src/main/java/org/talend/mdm/workbench/serverexplorer/ui/dialogs/ServerDefDialog.java
main/plugins/org.talend.mdm.workbench/src/com/amalto/workbench/utils/PasswordUtil.java
test/plugins/org.talend.mdm.repository.test/src/main/java/org/talend/mdm/repository/core/service/ConsistencyServiceTest.java
test/plugins/org.talend.mdm.workbench.test/src/main/java/com/amalto/workbench/utils/PasswordUtilTest.java

Using CryptoHelper to encrypt  and decrypt password.
Replace with new algorithm.
workitem

TMDM-13948 Remove CryptoHelper to use AES from mdm.

---

main/plugins/org.talend.mdm.workbench.serverexplorer/plugin.xml

Bug TMDM-14144 discovered after working on
https://jira.talendforge.org/browse/TMDM-13948
Modification of migration task's property has break the constraint.
Update the task's property to meet the constraint.

TMDM-13948 Change the migration task property to meet the migration task rule.

---

main/plugins/org.talend.mdm.workbench/src/com/amalto/workbench/utils/PasswordUtil.java
main/plugins/org.talend.mdm.workbench/src/com/amalto/workbench/utils/XSDUtil.java
test/plugins/org.talend.mdm.workbench.test/src/main/java/com/amalto/workbench/utils/PasswordUtilTest.java
test/plugins/org.talend.mdm.workbench.test/src/main/java/com/amalto/workbench/utils/XSDUtilTest.java

https://jira.talendforge.org/browse/TMDM-14194
Fix the test failure.

TMDM-14194 Fix the unit test failure.

---

test/plugins/org.talend.mdm.workbench.test/resources/ElementNameValidationDemo.xsd
test/plugins/org.talend.mdm.workbench.test/src/main/java/com/amalto/workbench/availablemodel/AvailableModelUtilTest.java
test/plugins/org.talend.mdm.workbench.test/src/main/java/com/amalto/workbench/utils/FKFilterParserTest.java
test/plugins/org.talend.mdm.workbench.test/src/main/java/com/amalto/workbench/utils/XmlUtilTest.java
test/plugins/org.talend.mdm.workbench.test/src/main/java/com/amalto/workbench/utils/inputvalidator/EditXSDEleDecNameValidatorTest.java
test/plugins/org.talend.mdm.workbench.test/src/main/java/com/amalto/workbench/utils/inputvalidator/EditXSDIdentityConstraintNameValidatorTest.java
test/plugins/org.talend.mdm.workbench.test/src/main/java/com/amalto/workbench/utils/inputvalidator/ElementNameValidationRuleTest.java
test/plugins/org.talend.mdm.workbench.test/src/main/java/com/amalto/workbench/widgets/celleditor/DefaultXPathValidatorTest.java

https://jira.talendforge.org/browse/TMDM-14042
Add unit test to new validation rule, add missing copyright.

TMDM-14042 Validate element's name of data model schema

---

main/plugins/org.talend.mdm.workbench/src/com/amalto/workbench/utils/Util.java
test/plugins/org.talend.mdm.workbench.test/src/main/java/com/amalto/workbench/utils/UtilTest.java

Some class includes "com.sun XPathAPI " internal class.
link: https://jira.talendforge.org/browse/TMDM-13103
Replace com.sun XPathAPI and update related JUnit test cases.

TMDM-13103 Replace com.sun XPathAPI and update related JUnit test case.

---

main/plugins/org.talend.mdm.workbench/META-INF/MANIFEST.MF
main/plugins/org.talend.mdm.workbench/src/com/amalto/workbench/editors/RoutingRuleMainPage.java
main/plugins/org.talend.mdm.workbench/src/com/amalto/workbench/proposal/ContentProposalAdapterExtended.java
main/plugins/org.talend.mdm.workbench/src/com/amalto/workbench/proposal/ProposalUtils.java
main/plugins/org.talend.mdm.workbench/src/com/amalto/workbench/utils/WidgetUtils.java
main/plugins/org.talend.mdm.workbench/src/com/amalto/workbench/widgets/xmleditor/TriggerCallProcessSourcePage.java

https://jira.talendforge.org/browse/TMDM-10614
NullPointerException throwing and auto completion did not work
auto completion work without NPE.

TMDM-10614 NPE when define conditions using auto completion in trigger condition expression

---

test/plugins/org.talend.mdm.workbench.test/build.properties

One unit test failed.
Fix the unit test failure, by adding the test resource to build path.
Fix unit test.

TMDM-14480 Run and log Studio JUnits results for 7.3.1GA

---

main/plugins/org.talend.mdm.workbench/src/com/amalto/workbench/utils/Util.java

https://jira.talendforge.org/browse/TMDM-14565
Check mdm connection cannot work in mdm and di perspective at same time
Check mdm connection can work in mdm and di perspective at same time, by switch context class loader for webservice class creation.

TMDM-14565 Check mdm connection cannot work both in mdm and di perspective at same time

---

main/plugins/org.talend.mdm.repository/src/main/java/org/talend/mdm/repository/core/impl/recyclebin/RecycleBinContentProvider.java

https://jira.talendforge.org/browse/TUP-26735

fix(TUP-26735):Cannot see the contents of the Recycle bin

---

main/plugins/org.talend.mdm.workbench/src/com/amalto/workbench/utils/HttpClientUtil.java

https://jira.talendforge.org/browse/TUP-27716
Studio not working normally if username/password contains special characters, it does not influence server explorer and meta data mdm connection.
encoding username &password with UTF-8 to keep it worked as expected.

TUP-27716 Studio not working normally if username/password contains special characters.

---

main/plugins/org.talend.mdm.repository/src/main/java/org/talend/mdm/repository/utils/RepositoryResourceUtil.java
test/plugins/org.talend.mdm.repository.test/src/main/java/org/talend/mdm/repository/utils/RepositoryResourceUtilMockTest.java

https://jira.talendforge.org/browse/TUP-28434

TUP-28434 Fix RepositoryResourceUtilMockTest

---

main/plugins/org.talend.mdm.repository/src/main/java/org/talend/mdm/repository/core/command/CommandManager.java

https://jira.talendforge.org/browse/TUP-28434

feat(TUP-28434) add one method for test.

---

main/plugins/org.talend.mdm.repository/resources/system/datamodel/UpdateReport_0.1.item

https://jira.talendforge.org/browse/TUP-28800

Fix：TUP-28800 Signature:MDM: Exported project containing a default MDM item without signature

---

main/plugins/org.talend.designer.components.tomprovider/components/tMDMConnection/tMDMConnection_java.xml
main/plugins/org.talend.designer.components.tomprovider/components/tMDMDelete/tMDMDelete_java.xml
main/plugins/org.talend.designer.components.tomprovider/components/tMDMOutput/tMDMOutput_java.xml
main/plugins/org.talend.designer.components.tomprovider/components/tMDMReadConf/tMDMReadConf_java.xml
main/plugins/org.talend.designer.components.tomprovider/components/tMDMRouteRecord/tMDMRouteRecord_java.xml
main/plugins/org.talend.designer.components.tomprovider/components/tMDMSP/tMDMSP_java.xml
main/plugins/org.talend.designer.components.tomprovider/components/tMDMViewSearch/tMDMViewSearch_java.xml
main/plugins/org.talend.designer.components.tomprovider/components/tMDMWriteConf/tMDMWriteConf_java.xml

CXF with version of 3.3.4
Upgrade to 3.3.7

TMDM-14904 Update CXF to 3.3.7 due to CVE-2020-1954

---

main/plugins/org.talend.mdm.repository.model/model/MDMServerObject.ecore
main/plugins/org.talend.mdm.repository.model/model/MDMServerObject.genmodel
main/plugins/org.talend.mdm.repository.model/src/main/java/org/talend/mdm/repository/model/mdmserverobject/MdmserverobjectPackage.java
main/plugins/org.talend.mdm.repository.model/src/main/java/org/talend/mdm/repository/model/mdmserverobject/WSTransformerV2E.java
main/plugins/org.talend.mdm.repository.model/src/main/java/org/talend/mdm/repository/model/mdmserverobject/impl/MdmserverobjectPackageImpl.java
main/plugins/org.talend.mdm.repository.model/src/main/java/org/talend/mdm/repository/model/mdmserverobject/impl/WSTransformerV2EImpl.java
main/plugins/org.talend.mdm.repository/src/main/java/org/talend/mdm/repository/i18n/Messages.java
main/plugins/org.talend.mdm.repository/src/main/java/org/talend/mdm/repository/i18n/messages.properties
main/plugins/org.talend.mdm.repository/src/main/java/org/talend/mdm/repository/ui/editors/TransformerMainPage2.java
main/plugins/org.talend.mdm.workbench/src/com/amalto/workbench/editors/TransformerMainPage.java
main/plugins/org.talend.mdm.ws/pom_stubs.xml
main/plugins/org.talend.mdm.ws/src/com/amalto/workbench/webservices/WSTransformerV2.java

https://jira.talendforge.org/browse/TUP-29207
Add one field to webservice stub class, update cxf version to 3.3.7, add checkbox to before_saving type process.

feat(TUP-29207)  Add a checkbox Run the process with admin permissions for beforeSaving process

---

main/plugins/org.talend.mdm.workbench/src/com/amalto/workbench/dialogs/ImportExchangeOptionsDialog.java

https://jira.talendforge.org/browse/TUP-28891

TUP-28891:Shared Studio: Check which functions will write data into folder "temp" of Studio installation folder from code

---

test/plugins/org.talend.mdm.repository.test/META-INF/MANIFEST.MF

fix(TUP-29517): add ant dependency

---

main/plugins/org.talend.mdm.workbench/src/com/amalto/workbench/utils/LocalTreeObjectRepository.java

Import Server Objects from MDM server" hangs consuming high CPU when resources contains more data.
https://jira.talendforge.org/browse/TPS-4635

TPS-4635 fix displace resource node error during importing server objects.

---

README.md
i18n/plugins/org.talend.mdm.workbench.nl/plugin_en.properties
i18n/plugins/org.talend.mdm.workbench.nl/plugin_fr.properties
i18n/plugins/org.talend.mdm.workbench.nl/plugin_ja.properties
i18n/plugins/org.talend.mdm.workbench.nl/plugin_zh_CN.properties
main/plugins/org.talend.mdm.workbench/plugin.properties
test/plugins/org.talend.mdm.workbench.test/src/main/java/com/amalto/workbench/widgets/xmleditor/ExtensibleEditorContentTest.java

https://jira.talendforge.org/browse/TUP-30114

feat(TUP-30114) update copyright.

---

main/plugins/org.talend.mdm.repository/src/main/java/org/talend/mdm/repository/core/AbstractRepositoryAction.java
main/plugins/org.talend.mdm.repository/src/main/java/org/talend/mdm/repository/ui/actions/ConfigRepositoryFilterAction.java
main/plugins/org.talend.mdm.repository/src/main/java/org/talend/mdm/repository/ui/actions/DuplicateAction.java
main/plugins/org.talend.mdm.repository/src/main/java/org/talend/mdm/repository/ui/actions/ImportServerObjectAction.java
main/plugins/org.talend.mdm.repository/src/main/java/org/talend/mdm/repository/ui/actions/PasteAction.java
main/plugins/org.talend.mdm.repository/src/main/java/org/talend/mdm/repository/ui/starting/actions/AbstractShowViewAction.java
main/plugins/org.talend.mdm.repository/src/main/java/org/talend/mdm/repository/ui/starting/actions/ConnectToWebUIAction.java
main/plugins/org.talend.mdm.repository/src/main/java/org/talend/mdm/repository/ui/starting/actions/ShowRepositoryViewAction.java
main/plugins/org.talend.mdm.repository/src/main/java/org/talend/mdm/repository/ui/starting/actions/ShowServerExplorerAction.java
main/plugins/org.talend.mdm.workbench.serverexplorer/src/main/java/org/talend/mdm/workbench/serverexplorer/ui/actions/AddServerDefAction.java
main/plugins/org.talend.mdm.workbench.serverexplorer/src/main/java/org/talend/mdm/workbench/serverexplorer/ui/actions/RefreshServerDefAction.java
main/plugins/org.talend.mdm.workbench.serverexplorer/src/main/java/org/talend/mdm/workbench/serverexplorer/ui/actions/ShowServerConsoleAction.java
main/plugins/org.talend.mdm.workbench.serverexplorer/src/main/java/org/talend/mdm/workbench/serverexplorer/ui/views/ServerExplorer.java

https://jira.talendforge.org/browse/TUP-30953

feat(TUP-30953): record mdm repository actions.

---

main/plugins/org.talend.mdm.engines.client/src/org/talend/mdm/engines/client/ui/wizards/DeployOnMDMExportWizardPage.java

https://jira.talendforge.org/browse/TUP-30834

feat(TUP-30834) remove reference to JobJavaScriptsWSManager which used axis1.

---

main/plugins/org.talend.designer.components.tomprovider/components/tMDMConnection/tMDMConnection_java.xml
main/plugins/org.talend.designer.components.tomprovider/components/tMDMDelete/tMDMDelete_java.xml
main/plugins/org.talend.designer.components.tomprovider/components/tMDMOutput/tMDMOutput_java.xml
main/plugins/org.talend.designer.components.tomprovider/components/tMDMReadConf/tMDMReadConf_java.xml
main/plugins/org.talend.designer.components.tomprovider/components/tMDMRouteRecord/tMDMRouteRecord_java.xml
main/plugins/org.talend.designer.components.tomprovider/components/tMDMSP/tMDMSP_java.xml
main/plugins/org.talend.designer.components.tomprovider/components/tMDMViewSearch/tMDMViewSearch_java.xml
main/plugins/org.talend.designer.components.tomprovider/components/tMDMWriteConf/tMDMWriteConf_java.xml
main/plugins/org.talend.mdm.ws.jars/plugin.xml

https://jira.talendforge.org/browse/TUP-32544
add missing urlpath

fix(TUP-32544): [Bug] Miss jars when run mvn package for mdm/dq/esb

---

main/plugins/org.talend.mdm.repository/src/main/java/org/talend/mdm/repository/core/AbstractRepositoryAction.java
main/plugins/org.talend.mdm.repository/src/main/java/org/talend/mdm/repository/ui/actions/CopyUrlAction.java

fix(TUP-32815): There is no deploy menus for Resource
